spring:
  security:
    user:
      name: meo
      password: 123

  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=ecommerce;trustServerCertificate=true"
    username: TrucPham
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8181